// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// trustUpdate
NumericMatrix trustUpdate(NumericMatrix trust, NumericVector advisorId, NumericVector advisorAgrees, double updateRate);
RcppExport SEXP _adviseR_trustUpdate(SEXP trustSEXP, SEXP advisorIdSEXP, SEXP advisorAgreesSEXP, SEXP updateRateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type trust(trustSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type advisorId(advisorIdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type advisorAgrees(advisorAgreesSEXP);
    Rcpp::traits::input_parameter< double >::type updateRate(updateRateSEXP);
    rcpp_result_gen = Rcpp::wrap(trustUpdate(trust, advisorId, advisorAgrees, updateRate));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adviseR_trustUpdate", (DL_FUNC) &_adviseR_trustUpdate, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_adviseR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
