# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates the evolving trust scores based on agreement
#'
#' @param trust Matrix of trust values - dims = trials x advisors
#' @param advisorId ids of the advisor giving advice on each trial
#' @param advisorAgrees whether advisor agrees on each trial
#' @param updateRate amount to down/upweight trust given dis/agreement
#' @return New trust values after iterating through and up/downweighting trust
trustUpdate <- function(trust, advisorId, advisorAgrees, updateRate) {
    .Call(`_adviseR_trustUpdate`, trust, advisorId, advisorAgrees, updateRate)
}

